// Generated by scripts/generate-process-epoch-wire.py; do not edit.
use super::{check_scalar, Validate};
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Descriptor {
    pub protocol: String,
    pub node_id: String,
    pub node_incarnation: String,
    pub runtime_id: String,
    pub runtime_incarnation: String,
    pub guest_boot_id: String,
    pub enrollment_revision: u64,
    pub process_endpoint: String,
    pub guest_build_sha256: String,
    pub capabilities_sha256: String,
    pub managed: bool,
}
impl Validate for Descriptor {
    fn validate(&self) -> anyhow::Result<()> {
        check_scalar("protocol", &serde_json::to_value(&self.protocol)?)?;
        check_scalar("text", &serde_json::to_value(&self.node_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.node_incarnation)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.runtime_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.runtime_incarnation)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.guest_boot_id)?)?;
        check_scalar("positive", &serde_json::to_value(self.enrollment_revision)?)?;
        check_scalar("text", &serde_json::to_value(&self.process_endpoint)?)?;
        check_scalar("hash", &serde_json::to_value(&self.guest_build_sha256)?)?;
        check_scalar("hash", &serde_json::to_value(&self.capabilities_sha256)?)?;
        check_scalar("true", &serde_json::to_value(self.managed)?)?;
        super::validate_relations("Descriptor", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EpochBinding {
    pub protocol: String,
    pub tenant_id: String,
    pub sandbox_family: String,
    pub sandbox_id: String,
    pub transition_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub launch_id: Option<String>,
    pub operation_id: String,
    pub reserved_session_id: String,
    pub descriptor_sha256: String,
    pub node_id: String,
    pub node_incarnation: String,
    pub runtime_id: String,
    pub runtime_incarnation: String,
    pub guest_boot_id: String,
    pub enrollment_revision: u64,
    pub process_endpoint: String,
    pub guest_build_sha256: String,
    pub capabilities_sha256: String,
}
impl Validate for EpochBinding {
    fn validate(&self) -> anyhow::Result<()> {
        check_scalar("protocol", &serde_json::to_value(&self.protocol)?)?;
        check_scalar("text", &serde_json::to_value(&self.tenant_id)?)?;
        check_scalar("family", &serde_json::to_value(&self.sandbox_family)?)?;
        check_scalar("text", &serde_json::to_value(&self.sandbox_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.transition_id)?)?;
        if let Some(value) = &self.launch_id {
            check_scalar("uuid", &serde_json::to_value(value)?)?;
        }
        check_scalar("uuid", &serde_json::to_value(&self.operation_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.reserved_session_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.descriptor_sha256)?)?;
        check_scalar("text", &serde_json::to_value(&self.node_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.node_incarnation)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.runtime_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.runtime_incarnation)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.guest_boot_id)?)?;
        check_scalar("positive", &serde_json::to_value(self.enrollment_revision)?)?;
        check_scalar("text", &serde_json::to_value(&self.process_endpoint)?)?;
        check_scalar("hash", &serde_json::to_value(&self.guest_build_sha256)?)?;
        check_scalar("hash", &serde_json::to_value(&self.capabilities_sha256)?)?;
        super::validate_relations("EpochBinding", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SavedDispatchProof {
    pub dispatch_id: String,
    pub dispatch_request_sha256: String,
    pub dispatch_kind: String,
    pub creation_or_transition_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub launch_id: Option<String>,
    pub reserved_session_id: String,
    pub authority_revision: u64,
    pub exact_result_id: String,
    pub exact_result_sha256: String,
}
impl Validate for SavedDispatchProof {
    fn validate(&self) -> anyhow::Result<()> {
        check_scalar("uuid", &serde_json::to_value(&self.dispatch_id)?)?;
        check_scalar(
            "hash",
            &serde_json::to_value(&self.dispatch_request_sha256)?,
        )?;
        check_scalar("dispatch_kind", &serde_json::to_value(&self.dispatch_kind)?)?;
        check_scalar(
            "uuid",
            &serde_json::to_value(&self.creation_or_transition_id)?,
        )?;
        if let Some(value) = &self.launch_id {
            check_scalar("uuid", &serde_json::to_value(value)?)?;
        }
        check_scalar("uuid", &serde_json::to_value(&self.reserved_session_id)?)?;
        check_scalar("positive", &serde_json::to_value(self.authority_revision)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.exact_result_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.exact_result_sha256)?)?;
        super::validate_relations("SavedDispatchProof", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InitialAuthority {
    pub creation_id: String,
    pub owner_user_id: String,
    pub creation_generation: u64,
    pub provider_operation_key: String,
    pub provider_request_sha256: String,
}
impl Validate for InitialAuthority {
    fn validate(&self) -> anyhow::Result<()> {
        check_scalar("uuid", &serde_json::to_value(&self.creation_id)?)?;
        check_scalar("text", &serde_json::to_value(&self.owner_user_id)?)?;
        check_scalar("positive", &serde_json::to_value(self.creation_generation)?)?;
        check_scalar("text", &serde_json::to_value(&self.provider_operation_key)?)?;
        check_scalar(
            "hash",
            &serde_json::to_value(&self.provider_request_sha256)?,
        )?;
        super::validate_relations("InitialAuthority", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RestoreBridge {
    pub predecessor_descriptor_sha256: String,
    pub predecessor_runtime_id: String,
    pub predecessor_runtime_incarnation: String,
    pub predecessor_guest_boot_id: String,
    pub predecessor_enrollment_revision: u64,
    pub expected_session_id: String,
    pub seal_operation_id: String,
    pub seal_request_sha256: String,
    pub seal_receipt_id: String,
    pub seal_receipt_sha256: String,
    pub sealed_inventory_sha256: String,
    pub restore_launch_id: String,
    pub restore_request_sha256: String,
    pub restore_result_id: String,
    pub restore_result_sha256: String,
    pub destination_descriptor_sha256: String,
    pub destination_runtime_id: String,
    pub destination_runtime_incarnation: String,
    pub destination_guest_boot_id: String,
    pub destination_enrollment_revision: u64,
    pub reserved_session_id: String,
}
impl Validate for RestoreBridge {
    fn validate(&self) -> anyhow::Result<()> {
        check_scalar(
            "hash",
            &serde_json::to_value(&self.predecessor_descriptor_sha256)?,
        )?;
        check_scalar("uuid", &serde_json::to_value(&self.predecessor_runtime_id)?)?;
        check_scalar(
            "uuid",
            &serde_json::to_value(&self.predecessor_runtime_incarnation)?,
        )?;
        check_scalar(
            "uuid",
            &serde_json::to_value(&self.predecessor_guest_boot_id)?,
        )?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.predecessor_enrollment_revision)?,
        )?;
        check_scalar("uuid", &serde_json::to_value(&self.expected_session_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.seal_operation_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.seal_request_sha256)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.seal_receipt_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.seal_receipt_sha256)?)?;
        check_scalar(
            "hash",
            &serde_json::to_value(&self.sealed_inventory_sha256)?,
        )?;
        check_scalar("uuid", &serde_json::to_value(&self.restore_launch_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.restore_request_sha256)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.restore_result_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.restore_result_sha256)?)?;
        check_scalar(
            "hash",
            &serde_json::to_value(&self.destination_descriptor_sha256)?,
        )?;
        check_scalar("uuid", &serde_json::to_value(&self.destination_runtime_id)?)?;
        check_scalar(
            "uuid",
            &serde_json::to_value(&self.destination_runtime_incarnation)?,
        )?;
        check_scalar(
            "uuid",
            &serde_json::to_value(&self.destination_guest_boot_id)?,
        )?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.destination_enrollment_revision)?,
        )?;
        check_scalar("uuid", &serde_json::to_value(&self.reserved_session_id)?)?;
        super::validate_relations("RestoreBridge", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InitialBindRequest {
    pub authority_kind: String,
    pub binding: EpochBinding,
    pub saved_dispatch: SavedDispatchProof,
    pub initial_authority: InitialAuthority,
    pub adoption_id: String,
    pub adoption_revision: u64,
    pub adoption_sha256: String,
}
impl Validate for InitialBindRequest {
    fn validate(&self) -> anyhow::Result<()> {
        check_scalar("initial_kind", &serde_json::to_value(&self.authority_kind)?)?;
        (self.binding).validate()?;
        (self.saved_dispatch).validate()?;
        (self.initial_authority).validate()?;
        check_scalar("uuid", &serde_json::to_value(&self.adoption_id)?)?;
        check_scalar("positive", &serde_json::to_value(self.adoption_revision)?)?;
        check_scalar("hash", &serde_json::to_value(&self.adoption_sha256)?)?;
        super::validate_relations("InitialBindRequest", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TransitionBindRequest {
    pub authority_kind: String,
    pub binding: EpochBinding,
    pub saved_dispatch: SavedDispatchProof,
    pub expected_session_id: String,
    pub seal_operation_id: String,
    pub seal_request_sha256: String,
    pub seal_receipt_id: String,
    pub seal_receipt_sha256: String,
    pub sealed_inventory_sha256: String,
    pub prior_enrollment_revision: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub restore_bridge: Option<RestoreBridge>,
}
impl Validate for TransitionBindRequest {
    fn validate(&self) -> anyhow::Result<()> {
        check_scalar(
            "transition_kind",
            &serde_json::to_value(&self.authority_kind)?,
        )?;
        (self.binding).validate()?;
        (self.saved_dispatch).validate()?;
        check_scalar("uuid", &serde_json::to_value(&self.expected_session_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.seal_operation_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.seal_request_sha256)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.seal_receipt_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.seal_receipt_sha256)?)?;
        check_scalar(
            "hash",
            &serde_json::to_value(&self.sealed_inventory_sha256)?,
        )?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.prior_enrollment_revision)?,
        )?;
        if let Some(value) = &self.restore_bridge {
            (value).validate()?;
        }
        super::validate_relations("TransitionBindRequest", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SealRequest {
    pub binding: EpochBinding,
    pub expected_session_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retirement_authority_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retirement_authority_sha256: Option<String>,
}
impl Validate for SealRequest {
    fn validate(&self) -> anyhow::Result<()> {
        (self.binding).validate()?;
        check_scalar("uuid", &serde_json::to_value(&self.expected_session_id)?)?;
        if let Some(value) = &self.retirement_authority_id {
            check_scalar("uuid", &serde_json::to_value(value)?)?;
        }
        if let Some(value) = &self.retirement_authority_sha256 {
            check_scalar("hash", &serde_json::to_value(value)?)?;
        }
        super::validate_relations("SealRequest", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvidenceReference {
    pub evidence_class: String,
    pub evidence_id: String,
    pub evidence_sha256: String,
}
impl Validate for EvidenceReference {
    fn validate(&self) -> anyhow::Result<()> {
        check_scalar("evidence", &serde_json::to_value(&self.evidence_class)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.evidence_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.evidence_sha256)?)?;
        super::validate_relations("EvidenceReference", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SealReceipt {
    pub request: SealRequest,
    pub request_sha256: String,
    pub receipt_id: String,
    pub state: String,
    pub execution_outcome: String,
    pub affected_operations_sha256: String,
    pub evidence: EvidenceReference,
}
impl Validate for SealReceipt {
    fn validate(&self) -> anyhow::Result<()> {
        (self.request).validate()?;
        check_scalar("hash", &serde_json::to_value(&self.request_sha256)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.receipt_id)?)?;
        check_scalar("seal_state", &serde_json::to_value(&self.state)?)?;
        check_scalar(
            "execution_outcome",
            &serde_json::to_value(&self.execution_outcome)?,
        )?;
        check_scalar(
            "hash",
            &serde_json::to_value(&self.affected_operations_sha256)?,
        )?;
        (self.evidence).validate()?;
        super::validate_relations("SealReceipt", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BindReceipt {
    pub binding: EpochBinding,
    pub request_sha256: String,
    pub receipt_id: String,
    pub kind: String,
    pub state: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seal_receipt_sha256: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub adoption_sha256: Option<String>,
    pub node_ledger_revision: u64,
    pub guest_journal_revision: u64,
    pub evidence: EvidenceReference,
}
impl Validate for BindReceipt {
    fn validate(&self) -> anyhow::Result<()> {
        (self.binding).validate()?;
        check_scalar("hash", &serde_json::to_value(&self.request_sha256)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.receipt_id)?)?;
        check_scalar("bind_kind", &serde_json::to_value(&self.kind)?)?;
        check_scalar("bind_state", &serde_json::to_value(&self.state)?)?;
        if let Some(value) = &self.expected_session_id {
            check_scalar("uuid", &serde_json::to_value(value)?)?;
        }
        if let Some(value) = &self.seal_receipt_sha256 {
            check_scalar("hash", &serde_json::to_value(value)?)?;
        }
        if let Some(value) = &self.adoption_sha256 {
            check_scalar("hash", &serde_json::to_value(value)?)?;
        }
        check_scalar(
            "positive",
            &serde_json::to_value(self.node_ledger_revision)?,
        )?;
        check_scalar("uint", &serde_json::to_value(self.guest_journal_revision)?)?;
        (self.evidence).validate()?;
        super::validate_relations("BindReceipt", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LookupRequest {
    pub binding: EpochBinding,
    pub saved_request_sha256: String,
    pub nonce: String,
}
impl Validate for LookupRequest {
    fn validate(&self) -> anyhow::Result<()> {
        (self.binding).validate()?;
        check_scalar("hash", &serde_json::to_value(&self.saved_request_sha256)?)?;
        check_scalar("hash", &serde_json::to_value(&self.nonce)?)?;
        super::validate_relations("LookupRequest", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LookupResponse {
    pub binding: EpochBinding,
    pub request_sha256: String,
    pub state: String,
    pub node_ledger_revision: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receipt_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receipt_sha256: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub evidence: Option<EvidenceReference>,
}
impl Validate for LookupResponse {
    fn validate(&self) -> anyhow::Result<()> {
        (self.binding).validate()?;
        check_scalar("hash", &serde_json::to_value(&self.request_sha256)?)?;
        check_scalar("lookup_state", &serde_json::to_value(&self.state)?)?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.node_ledger_revision)?,
        )?;
        if let Some(value) = &self.receipt_id {
            check_scalar("uuid", &serde_json::to_value(value)?)?;
        }
        if let Some(value) = &self.receipt_sha256 {
            check_scalar("hash", &serde_json::to_value(value)?)?;
        }
        if let Some(value) = &self.evidence {
            (value).validate()?;
        }
        super::validate_relations("LookupResponse", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StreamBinding {
    pub binding: EpochBinding,
    pub stream_id: String,
    pub process_operation_id: String,
    pub terminal_incarnation: String,
    pub direction: String,
    pub authority_id: String,
    pub authority_sha256: String,
}
impl Validate for StreamBinding {
    fn validate(&self) -> anyhow::Result<()> {
        (self.binding).validate()?;
        check_scalar("uuid", &serde_json::to_value(&self.stream_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.process_operation_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.terminal_incarnation)?)?;
        check_scalar("direction", &serde_json::to_value(&self.direction)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.authority_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.authority_sha256)?)?;
        super::validate_relations("StreamBinding", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StreamOpenRequest {
    pub stream: StreamBinding,
}
impl Validate for StreamOpenRequest {
    fn validate(&self) -> anyhow::Result<()> {
        (self.stream).validate()?;
        super::validate_relations("StreamOpenRequest", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FrameRequest {
    pub stream: StreamBinding,
    pub sequence: u64,
    pub mutation_id: String,
    pub payload_length: u64,
    pub payload_sha256: String,
}
impl Validate for FrameRequest {
    fn validate(&self) -> anyhow::Result<()> {
        (self.stream).validate()?;
        check_scalar("positive", &serde_json::to_value(self.sequence)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.mutation_id)?)?;
        check_scalar("uint", &serde_json::to_value(self.payload_length)?)?;
        check_scalar("hash", &serde_json::to_value(&self.payload_sha256)?)?;
        super::validate_relations("FrameRequest", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GuestReceipt {
    pub binding: EpochBinding,
    pub request_sha256: String,
    pub receipt_id: String,
    pub evidence_class: String,
    pub outcome: String,
    pub guest_journal_revision: u64,
}
impl Validate for GuestReceipt {
    fn validate(&self) -> anyhow::Result<()> {
        (self.binding).validate()?;
        check_scalar("hash", &serde_json::to_value(&self.request_sha256)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.receipt_id)?)?;
        check_scalar("guest_class", &serde_json::to_value(&self.evidence_class)?)?;
        check_scalar("guest_outcome", &serde_json::to_value(&self.outcome)?)?;
        check_scalar("uint", &serde_json::to_value(self.guest_journal_revision)?)?;
        super::validate_relations("GuestReceipt", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NodeResponse {
    pub binding: EpochBinding,
    pub request_sha256: String,
    pub nonce: String,
    pub node_ledger_revision: u64,
    pub evidence: EvidenceReference,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guest_receipt_sha256: Option<String>,
}
impl Validate for NodeResponse {
    fn validate(&self) -> anyhow::Result<()> {
        (self.binding).validate()?;
        check_scalar("hash", &serde_json::to_value(&self.request_sha256)?)?;
        check_scalar("hash", &serde_json::to_value(&self.nonce)?)?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.node_ledger_revision)?,
        )?;
        (self.evidence).validate()?;
        if let Some(value) = &self.guest_receipt_sha256 {
            check_scalar("hash", &serde_json::to_value(value)?)?;
        }
        super::validate_relations("NodeResponse", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReleaseRequest {
    pub binding: EpochBinding,
    pub bind_receipt_id: String,
    pub bind_receipt_sha256: String,
    pub installed_session_id: String,
    pub installation_id: String,
    pub installation_revision: u64,
    pub installation_sha256: String,
    pub access_grant_id: String,
    pub access_grant_sha256: String,
    pub publication_revision: u64,
    pub access_grant_revision: u64,
    pub release_revision: u64,
    pub expected_provider_revision: u64,
    pub lease_not_after_unix_ms: u64,
}
impl Validate for ReleaseRequest {
    fn validate(&self) -> anyhow::Result<()> {
        (self.binding).validate()?;
        check_scalar("uuid", &serde_json::to_value(&self.bind_receipt_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.bind_receipt_sha256)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.installed_session_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.installation_id)?)?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.installation_revision)?,
        )?;
        check_scalar("hash", &serde_json::to_value(&self.installation_sha256)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.access_grant_id)?)?;
        check_scalar("hash", &serde_json::to_value(&self.access_grant_sha256)?)?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.publication_revision)?,
        )?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.access_grant_revision)?,
        )?;
        check_scalar("positive", &serde_json::to_value(self.release_revision)?)?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.expected_provider_revision)?,
        )?;
        check_scalar(
            "positive",
            &serde_json::to_value(self.lease_not_after_unix_ms)?,
        )?;
        super::validate_relations("ReleaseRequest", &serde_json::to_value(self)?)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SignedEnvelope {
    pub protocol: String,
    pub domain: String,
    pub signer: String,
    pub key_id: String,
    pub trust_revision: u64,
    pub audience: String,
    pub node_id: String,
    pub node_incarnation: String,
    pub runtime_id: String,
    pub runtime_incarnation: String,
    pub enrollment_revision: u64,
    pub descriptor_sha256: String,
    pub request_sha256: String,
    pub nonce: String,
    pub expires_at_unix_ms: u64,
    pub body_sha256: String,
}
impl Validate for SignedEnvelope {
    fn validate(&self) -> anyhow::Result<()> {
        check_scalar("protocol", &serde_json::to_value(&self.protocol)?)?;
        check_scalar("domain", &serde_json::to_value(&self.domain)?)?;
        check_scalar("text", &serde_json::to_value(&self.signer)?)?;
        check_scalar("text", &serde_json::to_value(&self.key_id)?)?;
        check_scalar("positive", &serde_json::to_value(self.trust_revision)?)?;
        check_scalar("text", &serde_json::to_value(&self.audience)?)?;
        check_scalar("text", &serde_json::to_value(&self.node_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.node_incarnation)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.runtime_id)?)?;
        check_scalar("uuid", &serde_json::to_value(&self.runtime_incarnation)?)?;
        check_scalar("positive", &serde_json::to_value(self.enrollment_revision)?)?;
        check_scalar("hash", &serde_json::to_value(&self.descriptor_sha256)?)?;
        check_scalar("hash", &serde_json::to_value(&self.request_sha256)?)?;
        check_scalar("hash", &serde_json::to_value(&self.nonce)?)?;
        check_scalar("positive", &serde_json::to_value(self.expires_at_unix_ms)?)?;
        check_scalar("hash", &serde_json::to_value(&self.body_sha256)?)?;
        super::validate_relations("SignedEnvelope", &serde_json::to_value(self)?)
    }
}
pub fn canonical(kind: &str, bytes: &[u8]) -> anyhow::Result<Vec<u8>> {
    match kind {
        "Descriptor" => {
            let v: Descriptor = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "EpochBinding" => {
            let v: EpochBinding = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "SavedDispatchProof" => {
            let v: SavedDispatchProof = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "InitialAuthority" => {
            let v: InitialAuthority = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "RestoreBridge" => {
            let v: RestoreBridge = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "InitialBindRequest" => {
            let v: InitialBindRequest = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "TransitionBindRequest" => {
            let v: TransitionBindRequest = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "SealRequest" => {
            let v: SealRequest = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "EvidenceReference" => {
            let v: EvidenceReference = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "SealReceipt" => {
            let v: SealReceipt = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "BindReceipt" => {
            let v: BindReceipt = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "LookupRequest" => {
            let v: LookupRequest = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "LookupResponse" => {
            let v: LookupResponse = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "StreamBinding" => {
            let v: StreamBinding = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "StreamOpenRequest" => {
            let v: StreamOpenRequest = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "FrameRequest" => {
            let v: FrameRequest = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "GuestReceipt" => {
            let v: GuestReceipt = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "NodeResponse" => {
            let v: NodeResponse = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "ReleaseRequest" => {
            let v: ReleaseRequest = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        "SignedEnvelope" => {
            let v: SignedEnvelope = serde_json::from_slice(bytes)?;
            v.validate()?;
            Ok(serde_json::to_vec(&v)?)
        }
        _ => anyhow::bail!("unknown process epoch record"),
    }
}
