#!/usr/bin/env python3
"""Generate fixed-order wire records. Changes require a new reviewed vector freeze."""
import json
from pathlib import Path
r=Path(__file__).resolve().parents[1]
s=json.loads((r/'testdata/process-epoch-vectors/v1/schema.json').read_text())
types=s['types']; enums=s['enums']
rust=['// Generated by scripts/generate-process-epoch-wire.py; do not edit.','use serde::{Deserialize, Serialize};','use super::{check_scalar, Validate};']
go=['// Code generated by scripts/generate-process-epoch-wire.py; DO NOT EDIT.','package processepoch','import "encoding/json"']
for name, fields in types.items():
 rust+=['#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]','#[serde(deny_unknown_fields)]',f'pub struct {name} {{']
 go+=[f'type {name} struct {{']
 for f in fields:
  n,t=f['name'],f['type']; optional=t.endswith('?'); t=t.rstrip('?')
  rt=t if t in types else ('u64' if t in ('uint','positive') else 'bool' if t=='true' else 'Vec<u8>' if t=='octets' else 'String')
  gt=t if t in types else ('uint64' if t in ('uint','positive') else 'bool' if t=='true' else '[]uint16' if t=='octets' else 'string')
  if optional: rust+=['    #[serde(default, skip_serializing_if = "Option::is_none")]']; rt='Option<'+rt+'>'; gt='*'+gt
  rust+=[f'    pub {n}: {rt},']
  gn=''.join(p.title() for p in n.split('_'))
  go+=[f' {gn} {gt} `json:"{n}'+(',omitempty' if optional else '')+'"`']
 rust+=['}',f'impl Validate for {name} {{',' fn validate(&self) -> anyhow::Result<()> {']
 go+=['}',f'func (v {name}) validate() error {{']
 for f in fields:
  n,t=f['name'],f['type']; optional=t.endswith('?'); t=t.rstrip('?'); gn=''.join(p.title() for p in n.split('_'))
  if optional:
   rust += [f' if let Some(value) = &self.{n} {{']
   go += [f' if v.{gn} != nil {{']
  rv='value' if optional else (f'self.{n}' if t in ('uint','positive','true') or t in types else f'&self.{n}'); gv=f'*v.{gn}' if optional else f'v.{gn}'
  rust += [f' ({rv}).validate()?;' if t in types else f' check_scalar("{t}", &serde_json::to_value({rv})?)?;']
  go += [f' if err := ({gv}).validate(); err != nil {{ return err }}' if t in types else f' if err := checkScalar("{t}", {gv}); err != nil {{ return err }}']
  if optional: rust+=[' }']; go+=[' }']
 rust += [f' super::validate_relations("{name}", &serde_json::to_value(self)?)',' }','}']; go += [f' return validateRelations("{name}", v)','}']
rust+=['pub fn canonical(kind: &str, bytes: &[u8]) -> anyhow::Result<Vec<u8>> {',' match kind {']
go+=['func decode(kind string, data []byte) ([]byte,error) {','switch kind {']
for n in types:
 rust+=[f' "{n}" => {{ let v: {n} = serde_json::from_slice(bytes)?; v.validate()?; Ok(serde_json::to_vec(&v)?) }},']
 go+=[f'case "{n}": var v {n}; if err := json.Unmarshal(data,&v); err != nil {{ return nil,err }}; if err := v.validate(); err != nil {{ return nil,err }}; return marshal(v)']
rust+=['_ => anyhow::bail!("unknown process epoch record"),','}','}']
go+=['default: return nil,errInvalid','}','}']
(r/'src/process_epoch/wire/generated.rs').write_text('\n'.join(rust)+'\n')
(r/'services/processepoch/generated.go').write_text('\n'.join(go)+'\n')
# Enum lists are also generated, so the fixture schema is the single vocabulary source.
(r/'src/process_epoch/wire/enums.rs').write_text('pub fn enum_values(kind: &str) -> Option<&\'static [&\'static str]> { match kind {\n'+''.join('"'+k+'" => Some(&['+','.join(json.dumps(x) for x in v)+']),\n' for k,v in enums.items())+'_ => None,\n}}\n')
(r/'services/processepoch/enums.go').write_text('package processepoch\nvar enumValues = map[string][]string{\n'+''.join(json.dumps(k)+': {'+','.join(json.dumps(x) for x in v)+'},\n' for k,v in enums.items())+'}\n')

import subprocess
(r/"services/processepoch/schema.json").write_bytes((r/"testdata/process-epoch-vectors/v1/schema.json").read_bytes())
subprocess.run(["gofmt","-w",str(r/"services/processepoch/generated.go"),str(r/"services/processepoch/enums.go")],check=True)
subprocess.run(["rustfmt","--edition","2021",str(r/"src/process_epoch/wire/generated.rs"),str(r/"src/process_epoch/wire/enums.rs")],check=True)
