package processepoch

var enumValues = map[string][]string{
	"protocol":                    {"agentenv-process-epoch-v1"},
	"family":                      {"legacy", "native"},
	"dispatch_kind":               {"create", "wake", "restore"},
	"initial_kind":                {"initial_creation"},
	"transition_kind":             {"epoch_transition"},
	"evidence":                    {"host_dispatch_recorded", "guest_reported", "host_scope_stopped"},
	"seal_state":                  {"sealed", "incomplete"},
	"execution_outcome":           {"drained", "scope_retired", "unknown"},
	"bind_kind":                   {"initial", "transition"},
	"bind_state":                  {"bound_closed", "incomplete"},
	"lookup_state":                {"closing", "execution_claimed", "effect_unknown", "completed", "bound_closed", "incomplete", "claimed", "completed_seal", "bind_pending", "bound", "release_pending", "released", "unknown", "dispatch_completed", "retired"},
	"direction":                   {"stdin", "pty-input", "output-only"},
	"guest_class":                 {"guest_reported"},
	"guest_outcome":               {"incomplete", "reported_complete"},
	"domain":                      {"agentenv-process-epoch/descriptor/v1", "agentenv-process-epoch/seal/v1", "agentenv-process-epoch/bind/v1", "agentenv-process-epoch/lookup/v1", "agentenv-process-epoch/initializer/v1", "agentenv-process-epoch/mutation/v1", "agentenv-process-epoch/stream-open/v1", "agentenv-process-epoch/frame/v1", "agentenv-process-epoch/guest-receipt/v1", "agentenv-process-epoch/node-response/v1", "agentenv-process-epoch/release/v1", "agentenv-process-epoch/retire/v1"},
	"release_outcome":             {"accepted", "incomplete", "released"},
	"receipt_kind":                {"seal", "bind", "release", "dispatch_result", "host_cessation", "dispatch_result_v2"},
	"result_dispatch_kind":        {"create", "restore"},
	"dispatch_outcome":            {"running", "failed", "unknown"},
	"retirement_reason":           {"policy_idle", "policy_exhausted", "owner_delete", "epoch_seal_retire"},
	"dispatch_result_protocol_v2": {"agentenv-process-epoch-dispatch-result-v2"},
}
