// Code generated by scripts/generate-process-epoch-wire.py; DO NOT EDIT.
package processepoch

import "encoding/json"

type Descriptor struct {
	Protocol           string `json:"protocol"`
	NodeId             string `json:"node_id"`
	NodeIncarnation    string `json:"node_incarnation"`
	RuntimeId          string `json:"runtime_id"`
	RuntimeIncarnation string `json:"runtime_incarnation"`
	GuestBootId        string `json:"guest_boot_id"`
	EnrollmentRevision uint64 `json:"enrollment_revision"`
	ProcessEndpoint    string `json:"process_endpoint"`
	GuestBuildSha256   string `json:"guest_build_sha256"`
	CapabilitiesSha256 string `json:"capabilities_sha256"`
	Managed            bool   `json:"managed"`
}

func (v Descriptor) validate() error {
	if err := checkScalar("protocol", v.Protocol); err != nil {
		return err
	}
	if err := checkScalar("text", v.NodeId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.NodeIncarnation); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.RuntimeId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.RuntimeIncarnation); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.GuestBootId); err != nil {
		return err
	}
	if err := checkScalar("positive", v.EnrollmentRevision); err != nil {
		return err
	}
	if err := checkScalar("text", v.ProcessEndpoint); err != nil {
		return err
	}
	if err := checkScalar("hash", v.GuestBuildSha256); err != nil {
		return err
	}
	if err := checkScalar("hash", v.CapabilitiesSha256); err != nil {
		return err
	}
	if err := checkScalar("true", v.Managed); err != nil {
		return err
	}
	return validateRelations("Descriptor", v)
}

type EpochBinding struct {
	Protocol           string  `json:"protocol"`
	TenantId           string  `json:"tenant_id"`
	SandboxFamily      string  `json:"sandbox_family"`
	SandboxId          string  `json:"sandbox_id"`
	TransitionId       string  `json:"transition_id"`
	LaunchId           *string `json:"launch_id,omitempty"`
	OperationId        string  `json:"operation_id"`
	ReservedSessionId  string  `json:"reserved_session_id"`
	DescriptorSha256   string  `json:"descriptor_sha256"`
	NodeId             string  `json:"node_id"`
	NodeIncarnation    string  `json:"node_incarnation"`
	RuntimeId          string  `json:"runtime_id"`
	RuntimeIncarnation string  `json:"runtime_incarnation"`
	GuestBootId        string  `json:"guest_boot_id"`
	EnrollmentRevision uint64  `json:"enrollment_revision"`
	ProcessEndpoint    string  `json:"process_endpoint"`
	GuestBuildSha256   string  `json:"guest_build_sha256"`
	CapabilitiesSha256 string  `json:"capabilities_sha256"`
}

func (v EpochBinding) validate() error {
	if err := checkScalar("protocol", v.Protocol); err != nil {
		return err
	}
	if err := checkScalar("text", v.TenantId); err != nil {
		return err
	}
	if err := checkScalar("family", v.SandboxFamily); err != nil {
		return err
	}
	if err := checkScalar("text", v.SandboxId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.TransitionId); err != nil {
		return err
	}
	if v.LaunchId != nil {
		if err := checkScalar("uuid", *v.LaunchId); err != nil {
			return err
		}
	}
	if err := checkScalar("uuid", v.OperationId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ReservedSessionId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.DescriptorSha256); err != nil {
		return err
	}
	if err := checkScalar("text", v.NodeId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.NodeIncarnation); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.RuntimeId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.RuntimeIncarnation); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.GuestBootId); err != nil {
		return err
	}
	if err := checkScalar("positive", v.EnrollmentRevision); err != nil {
		return err
	}
	if err := checkScalar("text", v.ProcessEndpoint); err != nil {
		return err
	}
	if err := checkScalar("hash", v.GuestBuildSha256); err != nil {
		return err
	}
	if err := checkScalar("hash", v.CapabilitiesSha256); err != nil {
		return err
	}
	return validateRelations("EpochBinding", v)
}

type SavedDispatchProof struct {
	DispatchId             string  `json:"dispatch_id"`
	DispatchRequestSha256  string  `json:"dispatch_request_sha256"`
	DispatchKind           string  `json:"dispatch_kind"`
	CreationOrTransitionId string  `json:"creation_or_transition_id"`
	LaunchId               *string `json:"launch_id,omitempty"`
	ReservedSessionId      string  `json:"reserved_session_id"`
	AuthorityRevision      uint64  `json:"authority_revision"`
	ExactResultId          string  `json:"exact_result_id"`
	ExactResultSha256      string  `json:"exact_result_sha256"`
}

func (v SavedDispatchProof) validate() error {
	if err := checkScalar("uuid", v.DispatchId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.DispatchRequestSha256); err != nil {
		return err
	}
	if err := checkScalar("dispatch_kind", v.DispatchKind); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.CreationOrTransitionId); err != nil {
		return err
	}
	if v.LaunchId != nil {
		if err := checkScalar("uuid", *v.LaunchId); err != nil {
			return err
		}
	}
	if err := checkScalar("uuid", v.ReservedSessionId); err != nil {
		return err
	}
	if err := checkScalar("positive", v.AuthorityRevision); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ExactResultId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.ExactResultSha256); err != nil {
		return err
	}
	return validateRelations("SavedDispatchProof", v)
}

type InitialAuthority struct {
	CreationId            string `json:"creation_id"`
	OwnerUserId           string `json:"owner_user_id"`
	CreationGeneration    uint64 `json:"creation_generation"`
	ProviderOperationKey  string `json:"provider_operation_key"`
	ProviderRequestSha256 string `json:"provider_request_sha256"`
}

func (v InitialAuthority) validate() error {
	if err := checkScalar("uuid", v.CreationId); err != nil {
		return err
	}
	if err := checkScalar("text", v.OwnerUserId); err != nil {
		return err
	}
	if err := checkScalar("positive", v.CreationGeneration); err != nil {
		return err
	}
	if err := checkScalar("text", v.ProviderOperationKey); err != nil {
		return err
	}
	if err := checkScalar("hash", v.ProviderRequestSha256); err != nil {
		return err
	}
	return validateRelations("InitialAuthority", v)
}

type RestoreBridge struct {
	PredecessorDescriptorSha256   string `json:"predecessor_descriptor_sha256"`
	PredecessorRuntimeId          string `json:"predecessor_runtime_id"`
	PredecessorRuntimeIncarnation string `json:"predecessor_runtime_incarnation"`
	PredecessorGuestBootId        string `json:"predecessor_guest_boot_id"`
	PredecessorEnrollmentRevision uint64 `json:"predecessor_enrollment_revision"`
	ExpectedSessionId             string `json:"expected_session_id"`
	SealOperationId               string `json:"seal_operation_id"`
	SealRequestSha256             string `json:"seal_request_sha256"`
	SealReceiptId                 string `json:"seal_receipt_id"`
	SealReceiptSha256             string `json:"seal_receipt_sha256"`
	SealedInventorySha256         string `json:"sealed_inventory_sha256"`
	RestoreLaunchId               string `json:"restore_launch_id"`
	RestoreRequestSha256          string `json:"restore_request_sha256"`
	RestoreResultId               string `json:"restore_result_id"`
	RestoreResultSha256           string `json:"restore_result_sha256"`
	DestinationDescriptorSha256   string `json:"destination_descriptor_sha256"`
	DestinationRuntimeId          string `json:"destination_runtime_id"`
	DestinationRuntimeIncarnation string `json:"destination_runtime_incarnation"`
	DestinationGuestBootId        string `json:"destination_guest_boot_id"`
	DestinationEnrollmentRevision uint64 `json:"destination_enrollment_revision"`
	ReservedSessionId             string `json:"reserved_session_id"`
}

func (v RestoreBridge) validate() error {
	if err := checkScalar("hash", v.PredecessorDescriptorSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.PredecessorRuntimeId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.PredecessorRuntimeIncarnation); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.PredecessorGuestBootId); err != nil {
		return err
	}
	if err := checkScalar("positive", v.PredecessorEnrollmentRevision); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ExpectedSessionId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.SealOperationId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.SealRequestSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.SealReceiptId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.SealReceiptSha256); err != nil {
		return err
	}
	if err := checkScalar("hash", v.SealedInventorySha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.RestoreLaunchId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.RestoreRequestSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.RestoreResultId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.RestoreResultSha256); err != nil {
		return err
	}
	if err := checkScalar("hash", v.DestinationDescriptorSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.DestinationRuntimeId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.DestinationRuntimeIncarnation); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.DestinationGuestBootId); err != nil {
		return err
	}
	if err := checkScalar("positive", v.DestinationEnrollmentRevision); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ReservedSessionId); err != nil {
		return err
	}
	return validateRelations("RestoreBridge", v)
}

type InitialBindRequest struct {
	AuthorityKind    string             `json:"authority_kind"`
	Binding          EpochBinding       `json:"binding"`
	SavedDispatch    SavedDispatchProof `json:"saved_dispatch"`
	InitialAuthority InitialAuthority   `json:"initial_authority"`
	AdoptionId       string             `json:"adoption_id"`
	AdoptionRevision uint64             `json:"adoption_revision"`
	AdoptionSha256   string             `json:"adoption_sha256"`
}

func (v InitialBindRequest) validate() error {
	if err := checkScalar("initial_kind", v.AuthorityKind); err != nil {
		return err
	}
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := (v.SavedDispatch).validate(); err != nil {
		return err
	}
	if err := (v.InitialAuthority).validate(); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.AdoptionId); err != nil {
		return err
	}
	if err := checkScalar("positive", v.AdoptionRevision); err != nil {
		return err
	}
	if err := checkScalar("hash", v.AdoptionSha256); err != nil {
		return err
	}
	return validateRelations("InitialBindRequest", v)
}

type TransitionBindRequest struct {
	AuthorityKind           string             `json:"authority_kind"`
	Binding                 EpochBinding       `json:"binding"`
	SavedDispatch           SavedDispatchProof `json:"saved_dispatch"`
	ExpectedSessionId       string             `json:"expected_session_id"`
	SealOperationId         string             `json:"seal_operation_id"`
	SealRequestSha256       string             `json:"seal_request_sha256"`
	SealReceiptId           string             `json:"seal_receipt_id"`
	SealReceiptSha256       string             `json:"seal_receipt_sha256"`
	SealedInventorySha256   string             `json:"sealed_inventory_sha256"`
	PriorEnrollmentRevision uint64             `json:"prior_enrollment_revision"`
	RestoreBridge           *RestoreBridge     `json:"restore_bridge,omitempty"`
}

func (v TransitionBindRequest) validate() error {
	if err := checkScalar("transition_kind", v.AuthorityKind); err != nil {
		return err
	}
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := (v.SavedDispatch).validate(); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ExpectedSessionId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.SealOperationId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.SealRequestSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.SealReceiptId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.SealReceiptSha256); err != nil {
		return err
	}
	if err := checkScalar("hash", v.SealedInventorySha256); err != nil {
		return err
	}
	if err := checkScalar("positive", v.PriorEnrollmentRevision); err != nil {
		return err
	}
	if v.RestoreBridge != nil {
		if err := (*v.RestoreBridge).validate(); err != nil {
			return err
		}
	}
	return validateRelations("TransitionBindRequest", v)
}

type SealRequest struct {
	Binding                   EpochBinding `json:"binding"`
	ExpectedSessionId         string       `json:"expected_session_id"`
	RetirementAuthorityId     *string      `json:"retirement_authority_id,omitempty"`
	RetirementAuthoritySha256 *string      `json:"retirement_authority_sha256,omitempty"`
}

func (v SealRequest) validate() error {
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ExpectedSessionId); err != nil {
		return err
	}
	if v.RetirementAuthorityId != nil {
		if err := checkScalar("uuid", *v.RetirementAuthorityId); err != nil {
			return err
		}
	}
	if v.RetirementAuthoritySha256 != nil {
		if err := checkScalar("hash", *v.RetirementAuthoritySha256); err != nil {
			return err
		}
	}
	return validateRelations("SealRequest", v)
}

type EvidenceReference struct {
	EvidenceClass  string `json:"evidence_class"`
	EvidenceId     string `json:"evidence_id"`
	EvidenceSha256 string `json:"evidence_sha256"`
}

func (v EvidenceReference) validate() error {
	if err := checkScalar("evidence", v.EvidenceClass); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.EvidenceId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.EvidenceSha256); err != nil {
		return err
	}
	return validateRelations("EvidenceReference", v)
}

type SealReceipt struct {
	Request                  SealRequest       `json:"request"`
	RequestSha256            string            `json:"request_sha256"`
	ReceiptId                string            `json:"receipt_id"`
	State                    string            `json:"state"`
	ExecutionOutcome         string            `json:"execution_outcome"`
	AffectedOperationsSha256 string            `json:"affected_operations_sha256"`
	Evidence                 EvidenceReference `json:"evidence"`
}

func (v SealReceipt) validate() error {
	if err := (v.Request).validate(); err != nil {
		return err
	}
	if err := checkScalar("hash", v.RequestSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ReceiptId); err != nil {
		return err
	}
	if err := checkScalar("seal_state", v.State); err != nil {
		return err
	}
	if err := checkScalar("execution_outcome", v.ExecutionOutcome); err != nil {
		return err
	}
	if err := checkScalar("hash", v.AffectedOperationsSha256); err != nil {
		return err
	}
	if err := (v.Evidence).validate(); err != nil {
		return err
	}
	return validateRelations("SealReceipt", v)
}

type BindReceipt struct {
	Binding              EpochBinding      `json:"binding"`
	RequestSha256        string            `json:"request_sha256"`
	ReceiptId            string            `json:"receipt_id"`
	Kind                 string            `json:"kind"`
	State                string            `json:"state"`
	ExpectedSessionId    *string           `json:"expected_session_id,omitempty"`
	SealReceiptSha256    *string           `json:"seal_receipt_sha256,omitempty"`
	AdoptionSha256       *string           `json:"adoption_sha256,omitempty"`
	NodeLedgerRevision   uint64            `json:"node_ledger_revision"`
	GuestJournalRevision uint64            `json:"guest_journal_revision"`
	Evidence             EvidenceReference `json:"evidence"`
}

func (v BindReceipt) validate() error {
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := checkScalar("hash", v.RequestSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ReceiptId); err != nil {
		return err
	}
	if err := checkScalar("bind_kind", v.Kind); err != nil {
		return err
	}
	if err := checkScalar("bind_state", v.State); err != nil {
		return err
	}
	if v.ExpectedSessionId != nil {
		if err := checkScalar("uuid", *v.ExpectedSessionId); err != nil {
			return err
		}
	}
	if v.SealReceiptSha256 != nil {
		if err := checkScalar("hash", *v.SealReceiptSha256); err != nil {
			return err
		}
	}
	if v.AdoptionSha256 != nil {
		if err := checkScalar("hash", *v.AdoptionSha256); err != nil {
			return err
		}
	}
	if err := checkScalar("positive", v.NodeLedgerRevision); err != nil {
		return err
	}
	if err := checkScalar("uint", v.GuestJournalRevision); err != nil {
		return err
	}
	if err := (v.Evidence).validate(); err != nil {
		return err
	}
	return validateRelations("BindReceipt", v)
}

type LookupRequest struct {
	Binding            EpochBinding `json:"binding"`
	SavedRequestSha256 string       `json:"saved_request_sha256"`
	Nonce              string       `json:"nonce"`
}

func (v LookupRequest) validate() error {
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := checkScalar("hash", v.SavedRequestSha256); err != nil {
		return err
	}
	if err := checkScalar("hash", v.Nonce); err != nil {
		return err
	}
	return validateRelations("LookupRequest", v)
}

type LookupResponse struct {
	Binding            EpochBinding       `json:"binding"`
	RequestSha256      string             `json:"request_sha256"`
	State              string             `json:"state"`
	NodeLedgerRevision uint64             `json:"node_ledger_revision"`
	ReceiptId          *string            `json:"receipt_id,omitempty"`
	ReceiptSha256      *string            `json:"receipt_sha256,omitempty"`
	Evidence           *EvidenceReference `json:"evidence,omitempty"`
}

func (v LookupResponse) validate() error {
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := checkScalar("hash", v.RequestSha256); err != nil {
		return err
	}
	if err := checkScalar("lookup_state", v.State); err != nil {
		return err
	}
	if err := checkScalar("positive", v.NodeLedgerRevision); err != nil {
		return err
	}
	if v.ReceiptId != nil {
		if err := checkScalar("uuid", *v.ReceiptId); err != nil {
			return err
		}
	}
	if v.ReceiptSha256 != nil {
		if err := checkScalar("hash", *v.ReceiptSha256); err != nil {
			return err
		}
	}
	if v.Evidence != nil {
		if err := (*v.Evidence).validate(); err != nil {
			return err
		}
	}
	return validateRelations("LookupResponse", v)
}

type StreamBinding struct {
	Binding             EpochBinding `json:"binding"`
	StreamId            string       `json:"stream_id"`
	ProcessOperationId  string       `json:"process_operation_id"`
	TerminalIncarnation string       `json:"terminal_incarnation"`
	Direction           string       `json:"direction"`
	AuthorityId         string       `json:"authority_id"`
	AuthoritySha256     string       `json:"authority_sha256"`
}

func (v StreamBinding) validate() error {
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.StreamId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ProcessOperationId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.TerminalIncarnation); err != nil {
		return err
	}
	if err := checkScalar("direction", v.Direction); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.AuthorityId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.AuthoritySha256); err != nil {
		return err
	}
	return validateRelations("StreamBinding", v)
}

type StreamOpenRequest struct {
	Stream StreamBinding `json:"stream"`
}

func (v StreamOpenRequest) validate() error {
	if err := (v.Stream).validate(); err != nil {
		return err
	}
	return validateRelations("StreamOpenRequest", v)
}

type FrameRequest struct {
	Stream        StreamBinding `json:"stream"`
	Sequence      uint64        `json:"sequence"`
	MutationId    string        `json:"mutation_id"`
	PayloadLength uint64        `json:"payload_length"`
	PayloadSha256 string        `json:"payload_sha256"`
}

func (v FrameRequest) validate() error {
	if err := (v.Stream).validate(); err != nil {
		return err
	}
	if err := checkScalar("positive", v.Sequence); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.MutationId); err != nil {
		return err
	}
	if err := checkScalar("uint", v.PayloadLength); err != nil {
		return err
	}
	if err := checkScalar("hash", v.PayloadSha256); err != nil {
		return err
	}
	return validateRelations("FrameRequest", v)
}

type GuestReceipt struct {
	Binding              EpochBinding `json:"binding"`
	RequestSha256        string       `json:"request_sha256"`
	ReceiptId            string       `json:"receipt_id"`
	EvidenceClass        string       `json:"evidence_class"`
	Outcome              string       `json:"outcome"`
	GuestJournalRevision uint64       `json:"guest_journal_revision"`
}

func (v GuestReceipt) validate() error {
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := checkScalar("hash", v.RequestSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.ReceiptId); err != nil {
		return err
	}
	if err := checkScalar("guest_class", v.EvidenceClass); err != nil {
		return err
	}
	if err := checkScalar("guest_outcome", v.Outcome); err != nil {
		return err
	}
	if err := checkScalar("uint", v.GuestJournalRevision); err != nil {
		return err
	}
	return validateRelations("GuestReceipt", v)
}

type NodeResponse struct {
	Binding            EpochBinding      `json:"binding"`
	RequestSha256      string            `json:"request_sha256"`
	Nonce              string            `json:"nonce"`
	NodeLedgerRevision uint64            `json:"node_ledger_revision"`
	Evidence           EvidenceReference `json:"evidence"`
	GuestReceiptSha256 *string           `json:"guest_receipt_sha256,omitempty"`
}

func (v NodeResponse) validate() error {
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := checkScalar("hash", v.RequestSha256); err != nil {
		return err
	}
	if err := checkScalar("hash", v.Nonce); err != nil {
		return err
	}
	if err := checkScalar("positive", v.NodeLedgerRevision); err != nil {
		return err
	}
	if err := (v.Evidence).validate(); err != nil {
		return err
	}
	if v.GuestReceiptSha256 != nil {
		if err := checkScalar("hash", *v.GuestReceiptSha256); err != nil {
			return err
		}
	}
	return validateRelations("NodeResponse", v)
}

type ReleaseRequest struct {
	Binding                  EpochBinding `json:"binding"`
	BindReceiptId            string       `json:"bind_receipt_id"`
	BindReceiptSha256        string       `json:"bind_receipt_sha256"`
	InstalledSessionId       string       `json:"installed_session_id"`
	InstallationId           string       `json:"installation_id"`
	InstallationRevision     uint64       `json:"installation_revision"`
	InstallationSha256       string       `json:"installation_sha256"`
	AccessGrantId            string       `json:"access_grant_id"`
	AccessGrantSha256        string       `json:"access_grant_sha256"`
	PublicationRevision      uint64       `json:"publication_revision"`
	AccessGrantRevision      uint64       `json:"access_grant_revision"`
	ReleaseRevision          uint64       `json:"release_revision"`
	ExpectedProviderRevision uint64       `json:"expected_provider_revision"`
	LeaseNotAfterUnixMs      uint64       `json:"lease_not_after_unix_ms"`
}

func (v ReleaseRequest) validate() error {
	if err := (v.Binding).validate(); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.BindReceiptId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.BindReceiptSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.InstalledSessionId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.InstallationId); err != nil {
		return err
	}
	if err := checkScalar("positive", v.InstallationRevision); err != nil {
		return err
	}
	if err := checkScalar("hash", v.InstallationSha256); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.AccessGrantId); err != nil {
		return err
	}
	if err := checkScalar("hash", v.AccessGrantSha256); err != nil {
		return err
	}
	if err := checkScalar("positive", v.PublicationRevision); err != nil {
		return err
	}
	if err := checkScalar("positive", v.AccessGrantRevision); err != nil {
		return err
	}
	if err := checkScalar("positive", v.ReleaseRevision); err != nil {
		return err
	}
	if err := checkScalar("positive", v.ExpectedProviderRevision); err != nil {
		return err
	}
	if err := checkScalar("positive", v.LeaseNotAfterUnixMs); err != nil {
		return err
	}
	return validateRelations("ReleaseRequest", v)
}

type SignedEnvelope struct {
	Protocol           string `json:"protocol"`
	Domain             string `json:"domain"`
	Signer             string `json:"signer"`
	KeyId              string `json:"key_id"`
	TrustRevision      uint64 `json:"trust_revision"`
	Audience           string `json:"audience"`
	NodeId             string `json:"node_id"`
	NodeIncarnation    string `json:"node_incarnation"`
	RuntimeId          string `json:"runtime_id"`
	RuntimeIncarnation string `json:"runtime_incarnation"`
	EnrollmentRevision uint64 `json:"enrollment_revision"`
	DescriptorSha256   string `json:"descriptor_sha256"`
	RequestSha256      string `json:"request_sha256"`
	Nonce              string `json:"nonce"`
	ExpiresAtUnixMs    uint64 `json:"expires_at_unix_ms"`
	BodySha256         string `json:"body_sha256"`
}

func (v SignedEnvelope) validate() error {
	if err := checkScalar("protocol", v.Protocol); err != nil {
		return err
	}
	if err := checkScalar("domain", v.Domain); err != nil {
		return err
	}
	if err := checkScalar("text", v.Signer); err != nil {
		return err
	}
	if err := checkScalar("text", v.KeyId); err != nil {
		return err
	}
	if err := checkScalar("positive", v.TrustRevision); err != nil {
		return err
	}
	if err := checkScalar("text", v.Audience); err != nil {
		return err
	}
	if err := checkScalar("text", v.NodeId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.NodeIncarnation); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.RuntimeId); err != nil {
		return err
	}
	if err := checkScalar("uuid", v.RuntimeIncarnation); err != nil {
		return err
	}
	if err := checkScalar("positive", v.EnrollmentRevision); err != nil {
		return err
	}
	if err := checkScalar("hash", v.DescriptorSha256); err != nil {
		return err
	}
	if err := checkScalar("hash", v.RequestSha256); err != nil {
		return err
	}
	if err := checkScalar("hash", v.Nonce); err != nil {
		return err
	}
	if err := checkScalar("positive", v.ExpiresAtUnixMs); err != nil {
		return err
	}
	if err := checkScalar("hash", v.BodySha256); err != nil {
		return err
	}
	return validateRelations("SignedEnvelope", v)
}
func decode(kind string, data []byte) ([]byte, error) {
	switch kind {
	case "Descriptor":
		var v Descriptor
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "EpochBinding":
		var v EpochBinding
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "SavedDispatchProof":
		var v SavedDispatchProof
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "InitialAuthority":
		var v InitialAuthority
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "RestoreBridge":
		var v RestoreBridge
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "InitialBindRequest":
		var v InitialBindRequest
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "TransitionBindRequest":
		var v TransitionBindRequest
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "SealRequest":
		var v SealRequest
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "EvidenceReference":
		var v EvidenceReference
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "SealReceipt":
		var v SealReceipt
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "BindReceipt":
		var v BindReceipt
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "LookupRequest":
		var v LookupRequest
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "LookupResponse":
		var v LookupResponse
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "StreamBinding":
		var v StreamBinding
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "StreamOpenRequest":
		var v StreamOpenRequest
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "FrameRequest":
		var v FrameRequest
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "GuestReceipt":
		var v GuestReceipt
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "NodeResponse":
		var v NodeResponse
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "ReleaseRequest":
		var v ReleaseRequest
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	case "SignedEnvelope":
		var v SignedEnvelope
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		if err := v.validate(); err != nil {
			return nil, err
		}
		return marshal(v)
	default:
		return nil, errInvalid
	}
}
